services:
  frontend:
    container_name: frontend
    image: zyreael/frontend:latest
    ports:
      - "4200:80"
    networks:
      - app
    depends_on:
      - backend

  backend:
    container_name: backend
    image: zyreael/backend:latest
    ports:
      - "8080:8080"
    volumes:
      - logs:/app/logs
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${MYSQL_DATABASE}
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - app
    depends_on:
      - db

  db:
    image: mysql:8.1
    container_name: ${MYSQL_NAME}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - app

volumes:
  db:
  logs:

networks:
  app:
