services:
  backend:
    container_name: my-backend-container
    image: my-backend-image
    build:
      context: ..
      dockerfile: utils/backend.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - logs:/app/logs
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${MYSQL_DATABASE}
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - backend
    depends_on:
      - db

  db:
    image: mysql:8.1
    container_name: ${MYSQL_NAME}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

volumes:
  db:
  logs:

networks:
  backend:
